# Generated by Django 3.0.4 on 2020-03-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='v_etudiant_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=500)),
                ('fname', models.CharField(max_length=500)),
                ('lname', models.CharField(max_length=500)),
                ('birthday', models.DateField(max_length=500)),
                ('adresse', models.CharField(max_length=500)),
                ('pere', models.CharField(max_length=500)),
                ('mere', models.CharField(max_length=500)),
                ('phone_pere', models.IntegerField()),
                ('phone_mere', models.IntegerField()),
                ('adresse_parent', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'v_etudiant_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=10, unique=True)),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('adresse', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pere', models.CharField(max_length=250)),
                ('mere', models.CharField(max_length=250)),
                ('phone_pere', models.CharField(max_length=50)),
                ('phone_mere', models.CharField(max_length=50)),
                ('adresse_parent', models.CharField(max_length=500)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Niveau'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Etudiant')),
            ],
        ),
    ]
