# Generated by Django 3.0.4 on 2020-03-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=10)),
                ('niveau', models.CharField(max_length=10)),
                ('matiere', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.Etudiant')),
            ],
        ),
    ]
